# Day 8: NumPy Basics – Arrays, Operations, and Matrix Multiplication:-

In [1]:
import numpy as np                       #np is the (alias) or we can say nickname.

In [4]:
#Creating my first array-

array=[23,34,32,65,54]
arr1=np.array(array)    #converting to the numpy array
arr1
type(arr1)              #type of array

numpy.ndarray

In [11]:
# Creating a one dimensional array:-
arr=np.array([23,21,2,34,434])
print(arr)
arr.ndim          #checking dimensional of an array

[ 23  21   2  34 434]


1

In [15]:
#Creating 2 dimensional array

arr2=np.array([[22,34,32],[22,98,88],[23,34,56]])
print(arr2)
arr2.ndim       #checking dimensional of an array

# or

array2=np.array([[22,34,32,22,98,88,23,34,56]])
print(array2)
array2.ndim   #checking dimensional of an array


[[22 34 32]
 [22 98 88]
 [23 34 56]]
[[22 34 32 22 98 88 23 34 56]]


2

In [18]:
# Creating 3 dimensional array:-

arr3=np.array([[[23,34,34]]])

print(arr3)
arr3.ndim



[[[23 34 34]]]


3

In [33]:
#accessing element (indexing):-

arr = np.arange(24).reshape(2, 3, 4)
print(arr)
print()

print(arr[0,1,1])  #accessing 1st row 1st column in block 1.

print("Accessing 1st block",arr[1]) #accessing 1st block.

print()

print(arr[1][1])  #accessing the 2nd row f 2nd column.

print()

print(arr[:,1,:])  #second raw of both blocks

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

5
Accessing 1st block [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[16 17 18 19]

[[ 4  5  6  7]
 [16 17 18 19]]


In [41]:
# slicing in the elements:-

x=([2,3,4,5,9,8,7,6,6,7,8,9])
var=np.array(x)
print(var)

print("slicing from 2 to 5 ->",var[2:5])

print("last 3 elements->",var[-3:])

print("resverse-->",var[::-1])

[2 3 4 5 9 8 7 6 6 7 8 9]
slicing from 2 to 5 -> [4 5 9]
last 3 elements-> [7 8 9]
resverse--> [9 8 7 6 6 7 8 9 5 4 3 2]


In [43]:
#Arithmetic operations in NumPy :-

In [56]:
# into existing array-

# addition-
x=np.array([45600,5409,32450,87690,34591])
print(x)
print("adding 1325-->",x + 1325)        #adding 1325 into existing array.(it adds in each element).

print()

#Subtraction-

print("subtract by 1325-->",x-1325)

print()

#multiplication-

print("multiply by 1325-->",x*1325)

print()

#division-

print("division by 1325-->",x/1325)

[45600  5409 32450 87690 34591]
adding 1325--> [46925  6734 33775 89015 35916]

subtract by 1325--> [44275  4084 31125 86365 33266]

multiply by 1325--> [ 60420000   7166925  42996250 116189250  45833075]

division by 1325--> [34.41509434  4.08226415 24.49056604 66.18113208 26.10641509]


In [62]:
# individually :-

#addition-
x=np.array([23,45,544,876,29,765])
y=np.array([243,76,35,765,987,98])
print("Addition-->",x+y)                 #add elements

# subtraction-
x=np.array([23,45,544,876,29,765])
y=np.array([243,76,35,765,987,98])
print("Subtraction-->",x-y)             #subtract elements 

#division-
x=np.array([23,45,544,876,29,765])
y=np.array([243,76,35,765,987,98])
print("Division-->",x/y)                #divisible elements

#multiplication-
x=np.array([23,45,544,876,29,765])
y=np.array([243,76,35,765,987,98])
print("Multiplication-->",x*y)          #multiply elements

Addition--> [ 266  121  579 1641 1016  863]
Subtraction--> [-220  -31  509  111 -958  667]
Division--> [ 0.09465021  0.59210526 15.54285714  1.14509804  0.02938197  7.80612245]
Multiplication--> [  5589   3420  19040 670140  28623  74970]


In [69]:
###Broadcasting In NumPy###:-


# Broadcasting allows NumPy to perform arithmetic operations on arrays of different shapes in a way that avoids explicit copying of data.

a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([10, 20, 30])

result = a + b
print(result)

print()
matrix2=np.array([[12,23,21],[23,11,41]])
row2=np.array([2,3,4])
result=matrix*row2

print(result)


#broadcasting error-

# x=np.array([1,2,3,4])
# y=np.array([5,6,7,8,9])         
# print(x+y)                      

# this throw an error because no. of elements are not same.

[[11 22 33]
 [14 25 36]]

[[ 2  6 12]
 [ 8 15 24]]


In [112]:
#Using Max/Min/Dot/sum:-


#Max/Min/dot/sum:-
arr=np.random.randint(1,100,(4,8))       #using random function
arr
print(arr)
arr.size               #size of arr
maximum_row=np.max(arr,axis=1) 
minimum_row=np.min(arr,axis=1) 
maximum_column=np.max(arr,axis=0)
minimum_column=np.min(arr,axis=0)

print()

print("Maxium values in rows of arr is -->",maximum_row)           #max values in row
print("Minimum values in rows of arr is -->",minimum_row)           #max values in row
print("Maximum values in column of arr is -->", maximum_column)
print("Minimum values in column of arr is -->", minimum_column)


dot=np.prod(arr)
print(dot)

[[30 64 24 30 73 74 11 32]
 [40 73 83 50  8 46 60  4]
 [61  1  7 44 59 43 30 37]
 [32 53 60 82 46 94 95 88]]

Maxium values in rows of arr is --> [74 83 61 95]
Minimum values in rows of arr is --> [11  4  1 32]
Maximum values in column of arr is --> [61 73 83 82 73 94 95 88]
Minimum values in column of arr is --> [30  1  7 30  8 43 11  4]
821308797669605376


In [117]:
#dot-product-

matrix=np.array([[23,34,22,32],[23,45,33,21],[22,23,21,13]])
vector=np.array([4,2,8,2])
result=np.dot(matrix,vector)
print(result)

[400 488 328]
